name: Purge Old Versions of file.txt

on:
  push:
  workflow_dispatch: {}
  schedule:
    - cron: '*/12 * * * *'
    
jobs:
  purge-old-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          pip install '.[test]'
      - name: Update file.txt
        run: |
          python f2_update.py
      - name: Commit updates
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update czmls with new content"  || exit 0

      - name: Install BFG Repo-Cleaner
        run: |
          wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -O bfg.jar
      - name: Purge old revisions of file.txt
        run: |
          java -jar bfg.jar --delete-files hmf2.iczml
          java -jar bfg.jar --delete-files fof2.czml
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
      - name: Force push rewritten history
        run: |
          git push origin --force --all
