name: Purge Old Versions of file.txt

on:
  push:
    branches:
      - main  # Adjust as necessary for your branch
  workflow_dispatch:

jobs:
  purge-old-versions:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the entire repository history.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install the BFG Repo-Cleaner.
      - name: Install BFG Repo-Cleaner
        run: |
          wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -O bfg.jar

      # 3. Run BFG to purge all previous revisions of file.txt.
      #    This command removes file.txt from every commit except the latest one where it is present.
      - name: Purge old revisions of file.txt
        run: |
          java -jar bfg.jar --delete-files hmf2.iczml
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      # 4. Force push the rewritten history to the remote repository.
      - name: Force push rewritten history
        run: |
          git push origin --force --all
