name: Purge Old Versions of file.txt

on:
  push:
    branches:
      - main  # Adjust if needed
  workflow_dispatch:

jobs:
  purge-old-versions:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the full repository history using your PAT.
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Update file.txt
        run: |
          python f2_update.py
          git commit -m "Update file.txt with new content"

      # 2. Install BFG Repo-Cleaner.
      - name: Install BFG Repo-Cleaner
        run: |
          wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -O bfg.jar

      # 3. Purge all previous revisions of file.txt (keeping the latest version).
      - name: Purge old revisions of file.txt
        run: |
          java -jar bfg.jar --delete-files hmf2.iczml
          java -jar bfg.jar --delete-files fof2.czml
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      # 4. Force push the rewritten history back to the repository.
      - name: Force push rewritten history
        run: |
          git push origin --force --all
